services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hitoka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /var/lib/postgresql/data/pgdata