services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hitoka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: this password is a secret
      PGDATA: /var/lib/postgresql/data/pgdata